// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://hlirkx7fjbh25kjnrdrqv55moe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:812be37b-ec2e-46ff-8be7-2fecaa4a1c04",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PVg16MAvR",
    "aws_user_pools_web_client_id": "2bjfkb6mjm7gpl7jia8iffb61p",
    "oauth": {}
};


export default awsmobile;
